import canonicalLaneMathlib.AdmissibleClass
import LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean.BooleanAlgebraStructure
import LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean.BooleanAlgebraHomomorphism
import LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean.StoneRepresentation
import LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean.BooleanAlgebraDuality
import LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean.BooleanAlgebraCompleteness
import LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean.FilterUltrafilter

namespace HautevilleHouse
namespace LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean

def ConstrainedBooleanAlgebraClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_boolean_algebra_endgame (A : AdmissibleClass) :
    ConstrainedBooleanAlgebraClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end LogicalAspectsBooleanAlgebrasLemmaCanonicalLaneLean
end HautevilleHouse